blank_issues_enabled: false
contact_links:
  - name: Bewitchment Discord
    url: https://discord.gg/FFwyxuB2Bq
    about: Join the Discord for suggestions. Please do not submit a GitHub issue for suggestions.
